services:
  db:
    image: docker.io/postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoonet
    # Optional: Add security options for better Podman compatibility
    security_opt:
      - label=disable
    
  web:
    image: docker.io/odoo:18.0
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${ODEV_PORT}:8018"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf:Z
      - ./addons:/mnt/extra-addons:Z
      - odoo-web-data:/var/lib/odoo
    networks:
      - odoonet
    depends_on:
      - db
    # Optional: Add security options for better Podman compatibility
    security_opt:
      - label=disable

volumes:
  odoo-db-data:
  odoo-web-data:

networks:
  odoonet:
